import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-blood',
    name: 'FIRST BLOOD',
    description: 'Execute and complete your very first mission.',
    icon: 'Sword',
    requirement: 'Complete 1 mission',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    rewardXp: 100,
    category: 'missions',
  },
  {
    id: 'ach-rising-hunter',
    name: 'RISING HUNTER',
    description: 'Awaken your dormant potential and reach Level 5.',
    icon: 'ShieldAlert',
    requirement: 'Reach Level 5',
    unlocked: false,
    progress: 1,
    maxProgress: 5,
    rewardXp: 200,
    category: 'levels',
  },
  {
    id: 'ach-consistency',
    name: 'CONSISTENCY',
    description: 'Maintain an unbroken mission streak for 7 consecutive days.',
    icon: 'Flame',
    requirement: '7-day streak',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
    rewardXp: 250,
    category: 'streak',
  },
  {
    id: 'ach-unstoppable',
    name: 'UNSTOPPABLE',
    description: 'Defy distraction and forge a relentless 30-day streak.',
    icon: 'Zap',
    requirement: '30-day streak',
    unlocked: false,
    progress: 0,
    maxProgress: 30,
    rewardXp: 1000,
    category: 'streak',
  },
  {
    id: 'ach-mission-master',
    name: 'MISSION MASTER',
    description: 'Clear 100 missions in total across your hunter career.',
    icon: 'Award',
    requirement: 'Complete 100 missions',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    rewardXp: 800,
    category: 'missions',
  },
  {
    id: 'ach-night-owl',
    name: 'NIGHT OWL',
    description: 'Complete 10 missions during the midnight hours (10:00 PM – 4:00 AM).',
    icon: 'Moon',
    requirement: 'Complete 10 late-night missions',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    rewardXp: 300,
    category: 'special',
  },
  {
    id: 'ach-focus-master',
    name: 'FOCUS MASTER',
    description: 'Immerse your consciousness and complete 20 deep focus sessions.',
    icon: 'Clock',
    requirement: 'Complete 20 focus sessions',
    unlocked: false,
    progress: 0,
    maxProgress: 20,
    rewardXp: 400,
    category: 'focus',
  },
  {
    id: 'ach-legend',
    name: 'LEGEND',
    description: 'Triumph over a high-stakes LEGENDARY tier mission.',
    icon: 'Crown',
    requirement: 'Complete 1 Legendary mission',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    rewardXp: 500,
    category: 'missions',
  },
  {
    id: 'ach-speedrunner',
    name: 'SPEEDRUNNER',
    description: 'Demonstrate hyper-execution by clearing 5 missions in a single 24-hour cycle.',
    icon: 'FastForward',
    requirement: 'Complete 5 missions in one day',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    rewardXp: 350,
    category: 'missions',
  },
  {
    id: 'ach-architect',
    name: 'ARCHITECT',
    description: 'Deconstruct complex objectives by creating 10 granular subtasks.',
    icon: 'GitBranch',
    requirement: 'Create 10 subtasks',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    rewardXp: 150,
    category: 'special',
  },
  {
    id: 'ach-perfect-day',
    name: 'PERFECT DAY',
    description: 'Clear every single mission scheduled on your calendar for today.',
    icon: 'CheckCircle2',
    requirement: 'Clear all daily missions',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    rewardXp: 300,
    category: 'special',
  },
  {
    id: 'ach-chrono-knight',
    name: 'CHRONO KNIGHT',
    description: 'Accumulate 500 total minutes inside the deep focus chamber.',
    icon: 'Hourglass',
    requirement: 'Accumulate 500 focus minutes',
    unlocked: false,
    progress: 0,
    maxProgress: 500,
    rewardXp: 600,
    category: 'focus',
  },
];
