import { Mission, User, UserSettings, FocusSession, XpTransaction } from '../types';
import { format, subDays, addDays } from 'date-fns';

const todayStr = format(new Date(), 'yyyy-MM-dd');
const yesterdayStr = format(subDays(new Date(), 1), 'yyyy-MM-dd');
const tomorrowStr = format(addDays(new Date(), 1), 'yyyy-MM-dd');
const inTwoDaysStr = format(addDays(new Date(), 2), 'yyyy-MM-dd');

export const INITIAL_SETTINGS: UserSettings = {
  themeIntensity: 'cyber',
  soundEnabled: true,
  soundVolume: 0.7,
  hapticsEnabled: true,
  notificationsEnabled: true,
  dailyBriefingEnabled: true,
  dailyBriefingTime: '08:00',
  eveningReviewEnabled: true,
  eveningReviewTime: '21:00',
  quietHoursStart: '22:30',
  quietHoursEnd: '07:00',
  weekStartDay: 'monday',
  dailyMissionGoal: 5,
  reducedMotion: false,
};

export const INITIAL_USER: User = {
  id: 'hunter-alpha-01',
  name: 'Ren Vanguard',
  email: 'ren.vanguard@zenin.network',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  level: 27,
  currentXp: 2450,
  totalXpEarned: 24850,
  currentStreak: 12,
  bestStreak: 27,
  lastActiveDate: todayStr,
  streakFreezeAvailable: 1,
  totalMissionsCompleted: 148,
  totalFocusMinutes: 1860,
  createdAt: format(subDays(new Date(), 45), 'yyyy-MM-dd'),
  isGuest: false,
};

export const SAMPLE_MISSIONS: Mission[] = [
  {
    id: 'm-1',
    userId: 'hunter-alpha-01',
    title: 'Complete website homepage redesign',
    description: 'Finalize responsive hero layout, dark mode contrast tokens, and interactive canvas particle header.',
    priority: 'EPIC',
    categoryId: 'cat-projects',
    status: 'active',
    dueDate: todayStr,
    dueTime: '18:00',
    recurrence: 'none',
    tags: ['design', 'frontend', 'v2'],
    subtasks: [
      { id: 'st-1', title: 'Create wireframes & Figma tokens', completed: true, createdAt: todayStr },
      { id: 'st-2', title: 'Code responsive navigation bar', completed: true, createdAt: todayStr },
      { id: 'st-3', title: 'Implement hero particle canvas', completed: false, createdAt: todayStr },
      { id: 'st-4', title: 'Verify contrast ratios (WCAG AAA)', completed: false, createdAt: todayStr },
    ],
    estimatedDuration: 90,
    xpReward: 200,
    createdAt: format(subDays(new Date(), 2), 'yyyy-MM-dd HH:mm:ss'),
    updatedAt: todayStr,
    favorite: true,
    archived: false,
    xpAwarded: false,
    notes: 'Remember to verify Safari backdrop-filter blur behavior.',
  },
  {
    id: 'm-2',
    userId: 'hunter-alpha-01',
    title: 'Prepare quarterly client presentation',
    description: 'Synthesize productivity metrics, sprint velocity charts, and key deliverables into executive deck.',
    priority: 'EPIC',
    categoryId: 'cat-work',
    status: 'active',
    dueDate: todayStr,
    dueTime: '16:30',
    recurrence: 'none',
    tags: ['client', 'executive', 'q3'],
    subtasks: [
      { id: 'st-5', title: 'Export Q3 velocity charts', completed: true, createdAt: todayStr },
      { id: 'st-6', title: 'Draft executive summary slide', completed: false, createdAt: todayStr },
      { id: 'st-7', title: 'Review with product lead', completed: false, createdAt: todayStr },
    ],
    estimatedDuration: 60,
    xpReward: 180,
    createdAt: format(subDays(new Date(), 1), 'yyyy-MM-dd HH:mm:ss'),
    updatedAt: todayStr,
    favorite: true,
    archived: false,
    xpAwarded: false,
  },
  {
    id: 'm-3',
    userId: 'hunter-alpha-01',
    title: '30-minute high-intensity workout',
    description: 'Interval training: Kettlebell swings, pull-ups, and sprint intervals to maintain physical stamina.',
    priority: 'RARE',
    categoryId: 'cat-fitness',
    status: 'active',
    dueDate: todayStr,
    dueTime: '20:00',
    recurrence: 'daily',
    tags: ['health', 'cardio', 'core'],
    subtasks: [
      { id: 'st-8', title: 'Dynamic warmup (5m)', completed: false, createdAt: todayStr },
      { id: 'st-9', title: 'Kettlebell & sprint intervals (20m)', completed: false, createdAt: todayStr },
      { id: 'st-10', title: 'Cooldown & mobility (5m)', completed: false, createdAt: todayStr },
    ],
    estimatedDuration: 30,
    xpReward: 80,
    createdAt: todayStr,
    updatedAt: todayStr,
    favorite: false,
    archived: false,
    xpAwarded: false,
  },
  {
    id: 'm-4',
    userId: 'hunter-alpha-01',
    title: 'Read 20 pages of System Architecture',
    description: 'Deep dive into distributed consensus and event-driven patterns in chapters 7 & 8.',
    priority: 'COMMON',
    categoryId: 'cat-learning',
    status: 'active',
    dueDate: todayStr,
    dueTime: '22:00',
    recurrence: 'daily',
    tags: ['reading', 'architecture', 'books'],
    subtasks: [],
    estimatedDuration: 25,
    xpReward: 40,
    createdAt: todayStr,
    updatedAt: todayStr,
    favorite: false,
    archived: false,
    xpAwarded: false,
  },
  {
    id: 'm-5',
    userId: 'hunter-alpha-01',
    title: 'Execute production database migration',
    description: 'Apply non-destructive schema migrations and verify replica synchronization.',
    priority: 'LEGENDARY',
    categoryId: 'cat-work',
    status: 'active',
    dueDate: tomorrowStr,
    dueTime: '23:00',
    recurrence: 'none',
    tags: ['critical', 'database', 'devops'],
    subtasks: [
      { id: 'st-11', title: 'Perform pre-migration dry run on staging', completed: true, createdAt: todayStr },
      { id: 'st-12', title: 'Backup primary cluster snapshots', completed: false, createdAt: todayStr },
      { id: 'st-13', title: 'Initiate rolling migration script', completed: false, createdAt: todayStr },
      { id: 'st-14', title: 'Run post-migration integrity tests', completed: false, createdAt: todayStr },
    ],
    estimatedDuration: 120,
    xpReward: 400,
    createdAt: todayStr,
    updatedAt: todayStr,
    favorite: true,
    archived: false,
    xpAwarded: false,
  },
  {
    id: 'm-6',
    userId: 'hunter-alpha-01',
    title: 'Pay monthly studio electricity bill',
    description: 'Settle commercial electricity utility via online banking portal.',
    priority: 'COMMON',
    categoryId: 'cat-finance',
    status: 'completed',
    dueDate: todayStr,
    dueTime: '12:00',
    recurrence: 'monthly',
    tags: ['utilities', 'finance'],
    subtasks: [],
    estimatedDuration: 10,
    xpReward: 35,
    createdAt: yesterdayStr,
    updatedAt: todayStr,
    completedAt: `${todayStr} 10:15:00`,
    favorite: false,
    archived: false,
    xpAwarded: true,
  },
  {
    id: 'm-7',
    userId: 'hunter-alpha-01',
    title: 'Review weekly strategic objectives',
    description: 'Audit completed milestones, recalculate sprint targets, and clear obsolete backlog items.',
    priority: 'RARE',
    categoryId: 'cat-personal',
    status: 'completed',
    dueDate: todayStr,
    dueTime: '09:00',
    recurrence: 'weekly',
    tags: ['planning', 'reflection'],
    subtasks: [
      { id: 'st-15', title: 'Score completed tasks vs commitments', completed: true, createdAt: todayStr },
      { id: 'st-16', title: 'Adjust focus targets for upcoming week', completed: true, createdAt: todayStr },
    ],
    estimatedDuration: 20,
    xpReward: 75,
    createdAt: yesterdayStr,
    updatedAt: todayStr,
    completedAt: `${todayStr} 08:45:00`,
    favorite: false,
    archived: false,
    xpAwarded: true,
  },
  {
    id: 'm-8',
    userId: 'hunter-alpha-01',
    title: 'Deep clean and organize sensory workspace',
    description: 'Cable management, dust filters, and reset dual monitor positioning for optimal ergonomics.',
    priority: 'COMMON',
    categoryId: 'cat-personal',
    status: 'active',
    dueDate: inTwoDaysStr,
    dueTime: '15:00',
    recurrence: 'none',
    tags: ['clean', 'workspace', 'gear'],
    subtasks: [],
    estimatedDuration: 30,
    xpReward: 30,
    createdAt: todayStr,
    updatedAt: todayStr,
    favorite: false,
    archived: false,
    xpAwarded: false,
  },
];

export const SAMPLE_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: 'f-1',
    missionId: 'm-1',
    missionTitle: 'Complete website homepage redesign',
    durationMinutes: 45,
    xpEarned: 90,
    completedAt: `${todayStr} 11:30:00`,
    type: 'pomodoro',
  },
  {
    id: 'f-2',
    missionId: 'm-2',
    missionTitle: 'Prepare quarterly client presentation',
    durationMinutes: 25,
    xpEarned: 50,
    completedAt: `${todayStr} 14:00:00`,
    type: 'pomodoro',
  },
  {
    id: 'f-3',
    missionId: 'm-4',
    missionTitle: 'Read 20 pages of System Architecture',
    durationMinutes: 25,
    xpEarned: 50,
    completedAt: `${yesterdayStr} 21:00:00`,
    type: 'pomodoro',
  },
];

export const SAMPLE_XP_TRANSACTIONS: XpTransaction[] = [
  {
    id: 'tx-1',
    sourceId: 'm-6',
    sourceType: 'mission',
    amount: 35,
    timestamp: `${todayStr} 10:15:00`,
  },
  {
    id: 'tx-2',
    sourceId: 'm-7',
    sourceType: 'mission',
    amount: 75,
    timestamp: `${todayStr} 08:45:00`,
  },
  {
    id: 'tx-3',
    sourceId: 'f-1',
    sourceType: 'focus',
    amount: 90,
    timestamp: `${todayStr} 11:30:00`,
  },
];
